### PR TITLE
Supporting compose functions for handleErrors

### PR DESCRIPTION
**Pull request by cezarsmpio**
We can use `handleErrors` with compose functions, for instance:

```js
const enhance = compose(
  handleErrors(true),
  handleValidation(schema),
  handleLogs('compact'),
  useCors,
);

module.exports = enhance((req, res) => {...});
```

### CODE REVIEW

**Comment by cezarlz** [comment]
This will break the compatibility with previous versions. Should we make a major version instead?

**Comment by cezarlz** [comment]
I'm going to write/update tests.

**Comment by onbjerg** [comment]
Hey! Are you still planning on implementing this or should I close it? 😊

**Comment by cezarsmpio** [comment]
Hey, sorry, I totally forgot about it, I think you can close it.

**Pull request closed without merging**
