### PR TITLE
Update index.js

### PR DESCRIPTION
**Pull request by tungv**
Add WWW-Authenticate challenge to headers for 401 responses.

Actually, I'm not sure whether this is a good idea. Just convenient.

### CODE REVIEW

**Comment by onbjerg** [comment]
Not really sure if this should be in the library itself. What's your use case?

**Comment by tungv** [comment]
my use case is: deep inside a stateless function which has no access to the `response` or even `request` object, I want to throw a 401 error using `throw createError(401)`. However, to comply with the specs, it has to add an `WWW-Authenticate` header with a challenge as its value to the response.

What I expect: I can `throw createError(401, message, { challenge: 'a challenge' })`

Solutions I can come up with:

1. pass `res` object down to every functions on the way (which I think is simple, just not look clean enough).
2. write a `try catch` block at some point and `setHeader` when it's 401 and has a challenge in payload (which is what I tried in this PR)

**Comment by onbjerg** [comment]
Alright, seems fair.

**Comment by tungv** [comment]
Cool! glad that you agree. Thanks for merging

**Comment by onbjerg** [comment]
I've published it to npm now. Thanks for your contribution 🎉

**Pull request merged**
